/** Declaration file generated by dts-gen */
  
export = consistent_hashing;

declare class consistent_hashing {
    constructor(nodes: string[], options: any);

    addNode(node: string): void;

    compare(v1: string, v2: string): any;

    crypto(str: any): any;

    getNode(key: string): any;

    getNodePosition(hash: string): any;

    getRingLength(): number;

    removeNode(node: string): void;
}
