/** Declaration file generated by dts-gen */
  
export = consistent_hashing;

declare class consistent_hashing {
    constructor(nodes: any, options: any);

    addNode(node: any): void;

    compare(v1: any, v2: any): any;

    crypto(str: any): any;

    getNode(key: any): any;

    getNodePosition(hash: any): any;

    getRingLength(): any;

    removeNode(node: any): void;
}
