/** Declaration file generated by dts-gen */
  
export = consistent_hashing;

declare class consistent_hashing {
    constructor(nodes: string[], options: any);
    addNode(node: string): void;
    compare(v1: string, v2: string): number;
    crypto(str: string): string;
    getNode(key: string): string;
    getNodePosition(hash: string): number;
    getRingLength(): number;
    removeNode(node: string): void;
}
